# Generated by Django 3.2.9 on 2021-11-12 17:33

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cards_game_scoreboard_usergamecardstatus_usergamemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_token',
            field=models.IntegerField(default=cards.models.generate_unique_code),
        ),
    ]
